### ISSUE TITLE
SQL Transaction error on creating News

### ISSUE THREAD

**Issue by maexbower** [Philhil/DienstplanDLRG#13]
got a sql error when creating a news on a mobile device on fast network connection. Will provide Screenshot after reproducing it.

**Comment by Philhil** [comment]
It seems like some issues on the production machine with queuing and mail. Working in Dev environement.

**Comment by Philhil** [comment]
(1/2) SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction

(2/2) SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction (SQL: insert into `jobs` (`queue`, `payload`, `attempts`, `reserved_at`, `available_at`, `created_at`) values (default, ...
