### ISSUE TITLE
no check for manually asigning an user to multiple services

### ISSUE THREAD

**Issue by maexbower** [Philhil/DienstplanDLRG#16]
Its possible to select a user for more than one service in the change service view.
![grafik](https://user-images.githubusercontent.com/15195594/30313256-022b8e08-979d-11e7-91d0-3ea7d4415b73.png)

![grafik](https://user-images.githubusercontent.com/15195594/30313221-e33fbe24-979c-11e7-9d67-6ae5e99fc472.png)

**Comment by Philhil** [comment]
this not a bug, its a feature ;)

as admin you should have the possibility to set who ever you want at a position. Even if there are not the right qualification or has already an other position.
This could be helpfull if you want to set a cook or a person in two position at a simulation....
