### ISSUE TITLE
not assigned position counter should only count must have positions

### ISSUE THREAD

**Issue by Philhil** [Philhil/DienstplanDLRG#35]
"not assigned position counter" (on service overwiev) should only count must have positons.
 

- [x] positions: add bool if positions is a must have position
- [x] qualification:  position with a qualification is a must have (default)  
- [x] update Doku

**Comment by destroyer20121** [comment]
Moin sag mal wäre es mir möglich bei der Installation zu helfen? Ich würde gerne es mal testen

**Comment by Philhil** [comment]
Ich bin nicht ganz sicher was du meinst. Du kannst gerne zu jeder Zeit
etwas mit programmieren.

Die Tests zu neu entwickelten Funktionen laufen bei mir in der
Testumgebung. Diese ist aus dem allgemeinen Internet nicht erreichbar.

Am 05.06.2018 um 23:12 schrieb destroyer20121:

**Comment by destroyer20121** [comment]
Also ich meinte es das ich auf der Suche bin nach ein Wachpan für meine OG. Wenn ich es richtig gelesen habe ist es ja möglich dieses auf einem Server zu installieren. Mein Problem wäre nur das ich nicht die Ahnung habe es machen zu können.

**Comment by Philhil** [comment]
@destroyer20121 schreib mit mal eine E-Mail:  `dienste@bez-stuttgart.dlrg.de`
